baseURL: "https://barraroantree.github.io/" 
title: Barra Roantree
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

social:
    twitter: barratree

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: /research/
          weight: 1
        - name: Teaching
          url: /Teaching/
          weight: 2
        - name: Policy reports
          url: /policy/
          weight: 3
        - name: Newsletter
          url: https://howtotaxandspendit.substack.com/
          weight: 4

params:
    description: "I am an Assistant Professor of Economics at Trintiy College Dublin. My research focuses on the design of the tax and welfare system, and the evolution and distribution of living standards in Ireland."
    author: Barra Roantree
    googleAnalyticsID: "UA-105108701-1"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Barra Roantree
          subtitle: "I'm an Assistant Professor in Economics and Programme Director of the MSc in Economic Policy at Trinity College Dublin. My research focuses on the design of the tax and welfare system, and the evolution and distribution of living standards in Ireland. I previously worked as an economist at the Economic and Social Research Institute (ESRI) in Dublin and the Institute for Fiscal Studies (IFS) in London. I was a member of the Irish Government's 2021-22 Commission on Taxation and Welfare."
          imageUrl: "/picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Barra Roantree
          buttons:
            - name: Research
              url: /research/
            - name: Teaching
              url: /Teaching/
            - name: Policy Reports
              url: /policy/
            - name: Newsletter
              url: https://howtotaxandspendit.substack.com/
    socialIcons:
        - name: CV
          url: /cv.pdf
        - name: Email
          url: mailto:barra.roantree@tcd.ie
        - name: Location
          url: /location/
        - name: Office Hours
          url: /officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=en&user=efmNnHUAAAAJ
        - name: Twitter
          url: https://x.com/barratree
        - name: GitHub
          url: https://github.com/barraroantree

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Barra Roantree"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
